package clineq.data;
// Generated Mar 6, 2016 3:14:38 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Messags generated by hbm2java
 */
public class Messags  implements java.io.Serializable {


     private String messageId;
     private Subjects subjects;
     private Users users;
     private String eqStudyId;
     private String messageType;
     private String toDestination;
     private Date sendReceiveDate;
     private String withUploadDoc;
     private String uploadId;
     private String message;

    public Messags() {
    }

	
    public Messags(String messageId) {
        this.messageId = messageId;
    }
    public Messags(String messageId, Subjects subjects, Users users, String eqStudyId, String messageType, String toDestination, Date sendReceiveDate, String withUploadDoc, String uploadId, String message) {
       this.messageId = messageId;
       this.subjects = subjects;
       this.users = users;
       this.eqStudyId = eqStudyId;
       this.messageType = messageType;
       this.toDestination = toDestination;
       this.sendReceiveDate = sendReceiveDate;
       this.withUploadDoc = withUploadDoc;
       this.uploadId = uploadId;
       this.message = message;
    }
   
    public String getMessageId() {
        return this.messageId;
    }
    
    public void setMessageId(String messageId) {
        this.messageId = messageId;
    }
    public Subjects getSubjects() {
        return this.subjects;
    }
    
    public void setSubjects(Subjects subjects) {
        this.subjects = subjects;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public String getEqStudyId() {
        return this.eqStudyId;
    }
    
    public void setEqStudyId(String eqStudyId) {
        this.eqStudyId = eqStudyId;
    }
    public String getMessageType() {
        return this.messageType;
    }
    
    public void setMessageType(String messageType) {
        this.messageType = messageType;
    }
    public String getToDestination() {
        return this.toDestination;
    }
    
    public void setToDestination(String toDestination) {
        this.toDestination = toDestination;
    }
    public Date getSendReceiveDate() {
        return this.sendReceiveDate;
    }
    
    public void setSendReceiveDate(Date sendReceiveDate) {
        this.sendReceiveDate = sendReceiveDate;
    }
    public String getWithUploadDoc() {
        return this.withUploadDoc;
    }
    
    public void setWithUploadDoc(String withUploadDoc) {
        this.withUploadDoc = withUploadDoc;
    }
    public String getUploadId() {
        return this.uploadId;
    }
    
    public void setUploadId(String uploadId) {
        this.uploadId = uploadId;
    }
    public String getMessage() {
        return this.message;
    }
    
    public void setMessage(String message) {
        this.message = message;
    }




}


