package clineq.data;
// Generated Mar 6, 2016 3:14:38 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * OrgDetail generated by hbm2java
 */
public class OrgDetail  implements java.io.Serializable {


     private OrgDetailId id;
     private Organizations organizations;
     private String itemValue;
     private String itemDataType;
     private Date lastUpdateDate;

    public OrgDetail() {
    }

	
    public OrgDetail(OrgDetailId id, Organizations organizations) {
        this.id = id;
        this.organizations = organizations;
    }
    public OrgDetail(OrgDetailId id, Organizations organizations, String itemValue, String itemDataType, Date lastUpdateDate) {
       this.id = id;
       this.organizations = organizations;
       this.itemValue = itemValue;
       this.itemDataType = itemDataType;
       this.lastUpdateDate = lastUpdateDate;
    }
   
    public OrgDetailId getId() {
        return this.id;
    }
    
    public void setId(OrgDetailId id) {
        this.id = id;
    }
    public Organizations getOrganizations() {
        return this.organizations;
    }
    
    public void setOrganizations(Organizations organizations) {
        this.organizations = organizations;
    }
    public String getItemValue() {
        return this.itemValue;
    }
    
    public void setItemValue(String itemValue) {
        this.itemValue = itemValue;
    }
    public String getItemDataType() {
        return this.itemDataType;
    }
    
    public void setItemDataType(String itemDataType) {
        this.itemDataType = itemDataType;
    }
    public Date getLastUpdateDate() {
        return this.lastUpdateDate;
    }
    
    public void setLastUpdateDate(Date lastUpdateDate) {
        this.lastUpdateDate = lastUpdateDate;
    }




}


