package clineq.data;
// Generated Mar 6, 2016 3:14:38 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * SiteLocations generated by hbm2java
 */
public class SiteLocations  implements java.io.Serializable {


     private String eqLocationId;
     private String eqSiteId;
     private String sponSiteId;
     private String address1;
     private String address2;
     private String city;
     private String state;
     private String country;
     private String phone;
     private String zip;
     private String emrType;
     private String siteLocationName;
     private Set<StudyLocationMap> studyLocationMaps = new HashSet<StudyLocationMap>(0);

    public SiteLocations() {
    }

	
    public SiteLocations(String eqLocationId) {
        this.eqLocationId = eqLocationId;
    }
    public SiteLocations(String eqLocationId, String eqSiteId, String sponSiteId, String address1, String address2, String city, String state, String country, String phone, String zip, String emrType, String siteLocationName, Set<StudyLocationMap> studyLocationMaps) {
       this.eqLocationId = eqLocationId;
       this.eqSiteId = eqSiteId;
       this.sponSiteId = sponSiteId;
       this.address1 = address1;
       this.address2 = address2;
       this.city = city;
       this.state = state;
       this.country = country;
       this.phone = phone;
       this.zip = zip;
       this.emrType = emrType;
       this.siteLocationName = siteLocationName;
       this.studyLocationMaps = studyLocationMaps;
    }
   
    public String getEqLocationId() {
        return this.eqLocationId;
    }
    
    public void setEqLocationId(String eqLocationId) {
        this.eqLocationId = eqLocationId;
    }
    public String getEqSiteId() {
        return this.eqSiteId;
    }
    
    public void setEqSiteId(String eqSiteId) {
        this.eqSiteId = eqSiteId;
    }
    public String getSponSiteId() {
        return this.sponSiteId;
    }
    
    public void setSponSiteId(String sponSiteId) {
        this.sponSiteId = sponSiteId;
    }
    public String getAddress1() {
        return this.address1;
    }
    
    public void setAddress1(String address1) {
        this.address1 = address1;
    }
    public String getAddress2() {
        return this.address2;
    }
    
    public void setAddress2(String address2) {
        this.address2 = address2;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public String getState() {
        return this.state;
    }
    
    public void setState(String state) {
        this.state = state;
    }
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public String getZip() {
        return this.zip;
    }
    
    public void setZip(String zip) {
        this.zip = zip;
    }
    public String getEmrType() {
        return this.emrType;
    }
    
    public void setEmrType(String emrType) {
        this.emrType = emrType;
    }
    public String getSiteLocationName() {
        return this.siteLocationName;
    }
    
    public void setSiteLocationName(String siteLocationName) {
        this.siteLocationName = siteLocationName;
    }
    public Set<StudyLocationMap> getStudyLocationMaps() {
        return this.studyLocationMaps;
    }
    
    public void setStudyLocationMaps(Set<StudyLocationMap> studyLocationMaps) {
        this.studyLocationMaps = studyLocationMaps;
    }




}


