package clineq.data;
// Generated Mar 6, 2016 3:14:38 PM by Hibernate Tools 4.3.1



/**
 * StudySubjectMap generated by hbm2java
 */
public class StudySubjectMap  implements java.io.Serializable {


     private StudySubjectMapId id;
     private Studies studies;
     private Subjects subjects;
     private String status;

    public StudySubjectMap() {
    }

	
    public StudySubjectMap(StudySubjectMapId id, Studies studies, Subjects subjects) {
        this.id = id;
        this.studies = studies;
        this.subjects = subjects;
    }
    public StudySubjectMap(StudySubjectMapId id, Studies studies, Subjects subjects, String status) {
       this.id = id;
       this.studies = studies;
       this.subjects = subjects;
       this.status = status;
    }
   
    public StudySubjectMapId getId() {
        return this.id;
    }
    
    public void setId(StudySubjectMapId id) {
        this.id = id;
    }
    public Studies getStudies() {
        return this.studies;
    }
    
    public void setStudies(Studies studies) {
        this.studies = studies;
    }
    public Subjects getSubjects() {
        return this.subjects;
    }
    
    public void setSubjects(Subjects subjects) {
        this.subjects = subjects;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }




}


