package clineq.data;
// Generated Mar 6, 2016 3:14:38 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Studies generated by hbm2java
 */
public class Studies  implements java.io.Serializable {


     private String eqStudyId;
     private Organizations organizationsByEqIwrsId;
     private Organizations organizationsByEqSponId;
     private String eqCoSponId;
     private String nctid;
     private String euStudyId;
     private String studyAname;
     private String studyTitle;
     private String sponStudyId;
     private String coSponStudyId;
     private Date studyStartDate;
     private Date studyEndDate;
     private Date studyEqInitDate;
     private Date studyEqCloseDate;
     private BigDecimal plannedPatientsNum;
     private String chartGroupId;
     private String studyStatus;
     private Set<StudyUserMap> studyUserMaps = new HashSet<StudyUserMap>(0);
     private Set<StudyChartGroup> studyChartGroups = new HashSet<StudyChartGroup>(0);
     private Set<StudySubjectMap> studySubjectMaps = new HashSet<StudySubjectMap>(0);
     private Set<StudyLocationMap> studyLocationMaps = new HashSet<StudyLocationMap>(0);
     private Set<Subjects> subjectses = new HashSet<Subjects>(0);

    public Studies() {
    }

	
    public Studies(String eqStudyId) {
        this.eqStudyId = eqStudyId;
    }
    public Studies(String eqStudyId, Organizations organizationsByEqIwrsId, Organizations organizationsByEqSponId, String eqCoSponId, String nctid, String euStudyId, String studyAname, String studyTitle, String sponStudyId, String coSponStudyId, Date studyStartDate, Date studyEndDate, Date studyEqInitDate, Date studyEqCloseDate, BigDecimal plannedPatientsNum, String chartGroupId, String studyStatus, Set<StudyUserMap> studyUserMaps, Set<StudyChartGroup> studyChartGroups, Set<StudySubjectMap> studySubjectMaps, Set<StudyLocationMap> studyLocationMaps, Set<Subjects> subjectses) {
       this.eqStudyId = eqStudyId;
       this.organizationsByEqIwrsId = organizationsByEqIwrsId;
       this.organizationsByEqSponId = organizationsByEqSponId;
       this.eqCoSponId = eqCoSponId;
       this.nctid = nctid;
       this.euStudyId = euStudyId;
       this.studyAname = studyAname;
       this.studyTitle = studyTitle;
       this.sponStudyId = sponStudyId;
       this.coSponStudyId = coSponStudyId;
       this.studyStartDate = studyStartDate;
       this.studyEndDate = studyEndDate;
       this.studyEqInitDate = studyEqInitDate;
       this.studyEqCloseDate = studyEqCloseDate;
       this.plannedPatientsNum = plannedPatientsNum;
       this.chartGroupId = chartGroupId;
       this.studyStatus = studyStatus;
       this.studyUserMaps = studyUserMaps;
       this.studyChartGroups = studyChartGroups;
       this.studySubjectMaps = studySubjectMaps;
       this.studyLocationMaps = studyLocationMaps;
       this.subjectses = subjectses;
    }
   
    public String getEqStudyId() {
        return this.eqStudyId;
    }
    
    public void setEqStudyId(String eqStudyId) {
        this.eqStudyId = eqStudyId;
    }
    public Organizations getOrganizationsByEqIwrsId() {
        return this.organizationsByEqIwrsId;
    }
    
    public void setOrganizationsByEqIwrsId(Organizations organizationsByEqIwrsId) {
        this.organizationsByEqIwrsId = organizationsByEqIwrsId;
    }
    public Organizations getOrganizationsByEqSponId() {
        return this.organizationsByEqSponId;
    }
    
    public void setOrganizationsByEqSponId(Organizations organizationsByEqSponId) {
        this.organizationsByEqSponId = organizationsByEqSponId;
    }
    public String getEqCoSponId() {
        return this.eqCoSponId;
    }
    
    public void setEqCoSponId(String eqCoSponId) {
        this.eqCoSponId = eqCoSponId;
    }
    public String getNctid() {
        return this.nctid;
    }
    
    public void setNctid(String nctid) {
        this.nctid = nctid;
    }
    public String getEuStudyId() {
        return this.euStudyId;
    }
    
    public void setEuStudyId(String euStudyId) {
        this.euStudyId = euStudyId;
    }
    public String getStudyAname() {
        return this.studyAname;
    }
    
    public void setStudyAname(String studyAname) {
        this.studyAname = studyAname;
    }
    public String getStudyTitle() {
        return this.studyTitle;
    }
    
    public void setStudyTitle(String studyTitle) {
        this.studyTitle = studyTitle;
    }
    public String getSponStudyId() {
        return this.sponStudyId;
    }
    
    public void setSponStudyId(String sponStudyId) {
        this.sponStudyId = sponStudyId;
    }
    public String getCoSponStudyId() {
        return this.coSponStudyId;
    }
    
    public void setCoSponStudyId(String coSponStudyId) {
        this.coSponStudyId = coSponStudyId;
    }
    public Date getStudyStartDate() {
        return this.studyStartDate;
    }
    
    public void setStudyStartDate(Date studyStartDate) {
        this.studyStartDate = studyStartDate;
    }
    public Date getStudyEndDate() {
        return this.studyEndDate;
    }
    
    public void setStudyEndDate(Date studyEndDate) {
        this.studyEndDate = studyEndDate;
    }
    public Date getStudyEqInitDate() {
        return this.studyEqInitDate;
    }
    
    public void setStudyEqInitDate(Date studyEqInitDate) {
        this.studyEqInitDate = studyEqInitDate;
    }
    public Date getStudyEqCloseDate() {
        return this.studyEqCloseDate;
    }
    
    public void setStudyEqCloseDate(Date studyEqCloseDate) {
        this.studyEqCloseDate = studyEqCloseDate;
    }
    public BigDecimal getPlannedPatientsNum() {
        return this.plannedPatientsNum;
    }
    
    public void setPlannedPatientsNum(BigDecimal plannedPatientsNum) {
        this.plannedPatientsNum = plannedPatientsNum;
    }
    public String getChartGroupId() {
        return this.chartGroupId;
    }
    
    public void setChartGroupId(String chartGroupId) {
        this.chartGroupId = chartGroupId;
    }
    public String getStudyStatus() {
        return this.studyStatus;
    }
    
    public void setStudyStatus(String studyStatus) {
        this.studyStatus = studyStatus;
    }
    public Set<StudyUserMap> getStudyUserMaps() {
        return this.studyUserMaps;
    }
    
    public void setStudyUserMaps(Set<StudyUserMap> studyUserMaps) {
        this.studyUserMaps = studyUserMaps;
    }
    public Set<StudyChartGroup> getStudyChartGroups() {
        return this.studyChartGroups;
    }
    
    public void setStudyChartGroups(Set<StudyChartGroup> studyChartGroups) {
        this.studyChartGroups = studyChartGroups;
    }
    public Set<StudySubjectMap> getStudySubjectMaps() {
        return this.studySubjectMaps;
    }
    
    public void setStudySubjectMaps(Set<StudySubjectMap> studySubjectMaps) {
        this.studySubjectMaps = studySubjectMaps;
    }
    public Set<StudyLocationMap> getStudyLocationMaps() {
        return this.studyLocationMaps;
    }
    
    public void setStudyLocationMaps(Set<StudyLocationMap> studyLocationMaps) {
        this.studyLocationMaps = studyLocationMaps;
    }
    public Set<Subjects> getSubjectses() {
        return this.subjectses;
    }
    
    public void setSubjectses(Set<Subjects> subjectses) {
        this.subjectses = subjectses;
    }




}


