package clineq.data;
// Generated Mar 6, 2016 3:14:38 PM by Hibernate Tools 4.3.1



/**
 * StudyLocationMapId generated by hbm2java
 */
public class StudyLocationMapId  implements java.io.Serializable {


     private String eqStudyId;
     private String eqLocationId;

    public StudyLocationMapId() {
    }

    public StudyLocationMapId(String eqStudyId, String eqLocationId) {
       this.eqStudyId = eqStudyId;
       this.eqLocationId = eqLocationId;
    }
   
    public String getEqStudyId() {
        return this.eqStudyId;
    }
    
    public void setEqStudyId(String eqStudyId) {
        this.eqStudyId = eqStudyId;
    }
    public String getEqLocationId() {
        return this.eqLocationId;
    }
    
    public void setEqLocationId(String eqLocationId) {
        this.eqLocationId = eqLocationId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof StudyLocationMapId) ) return false;
		 StudyLocationMapId castOther = ( StudyLocationMapId ) other; 
         
		 return ( (this.getEqStudyId()==castOther.getEqStudyId()) || ( this.getEqStudyId()!=null && castOther.getEqStudyId()!=null && this.getEqStudyId().equals(castOther.getEqStudyId()) ) )
 && ( (this.getEqLocationId()==castOther.getEqLocationId()) || ( this.getEqLocationId()!=null && castOther.getEqLocationId()!=null && this.getEqLocationId().equals(castOther.getEqLocationId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getEqStudyId() == null ? 0 : this.getEqStudyId().hashCode() );
         result = 37 * result + ( getEqLocationId() == null ? 0 : this.getEqLocationId().hashCode() );
         return result;
   }   


}


