package clineq.data;
// Generated Mar 6, 2016 3:14:38 PM by Hibernate Tools 4.3.1



/**
 * StudyUserMap generated by hbm2java
 */
public class StudyUserMap  implements java.io.Serializable {


     private StudyUserMapId id;
     private Studies studies;
     private Users users;
     private String status;

    public StudyUserMap() {
    }

	
    public StudyUserMap(StudyUserMapId id, Studies studies, Users users) {
        this.id = id;
        this.studies = studies;
        this.users = users;
    }
    public StudyUserMap(StudyUserMapId id, Studies studies, Users users, String status) {
       this.id = id;
       this.studies = studies;
       this.users = users;
       this.status = status;
    }
   
    public StudyUserMapId getId() {
        return this.id;
    }
    
    public void setId(StudyUserMapId id) {
        this.id = id;
    }
    public Studies getStudies() {
        return this.studies;
    }
    
    public void setStudies(Studies studies) {
        this.studies = studies;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }




}


