package clineq.data;
// Generated Mar 6, 2016 3:14:38 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * StudySiteMap generated by hbm2java
 */
public class StudySiteMap  implements java.io.Serializable {


     private StudySiteMapId id;
     private Organizations organizations;
     private Date lastUpdateDate;
     private String status;

    public StudySiteMap() {
    }

	
    public StudySiteMap(StudySiteMapId id, Organizations organizations) {
        this.id = id;
        this.organizations = organizations;
    }
    public StudySiteMap(StudySiteMapId id, Organizations organizations, Date lastUpdateDate, String status) {
       this.id = id;
       this.organizations = organizations;
       this.lastUpdateDate = lastUpdateDate;
       this.status = status;
    }
   
    public StudySiteMapId getId() {
        return this.id;
    }
    
    public void setId(StudySiteMapId id) {
        this.id = id;
    }
    public Organizations getOrganizations() {
        return this.organizations;
    }
    
    public void setOrganizations(Organizations organizations) {
        this.organizations = organizations;
    }
    public Date getLastUpdateDate() {
        return this.lastUpdateDate;
    }
    
    public void setLastUpdateDate(Date lastUpdateDate) {
        this.lastUpdateDate = lastUpdateDate;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }




}


