package clineq.data;
// Generated Mar 6, 2016 3:14:38 PM by Hibernate Tools 4.3.1



/**
 * StudyLocationMap generated by hbm2java
 */
public class StudyLocationMap  implements java.io.Serializable {


     private StudyLocationMapId id;
     private SiteLocations siteLocations;
     private Studies studies;
     private String notes;

    public StudyLocationMap() {
    }

	
    public StudyLocationMap(StudyLocationMapId id, SiteLocations siteLocations, Studies studies) {
        this.id = id;
        this.siteLocations = siteLocations;
        this.studies = studies;
    }
    public StudyLocationMap(StudyLocationMapId id, SiteLocations siteLocations, Studies studies, String notes) {
       this.id = id;
       this.siteLocations = siteLocations;
       this.studies = studies;
       this.notes = notes;
    }
   
    public StudyLocationMapId getId() {
        return this.id;
    }
    
    public void setId(StudyLocationMapId id) {
        this.id = id;
    }
    public SiteLocations getSiteLocations() {
        return this.siteLocations;
    }
    
    public void setSiteLocations(SiteLocations siteLocations) {
        this.siteLocations = siteLocations;
    }
    public Studies getStudies() {
        return this.studies;
    }
    
    public void setStudies(Studies studies) {
        this.studies = studies;
    }
    public String getNotes() {
        return this.notes;
    }
    
    public void setNotes(String notes) {
        this.notes = notes;
    }




}


