package clineq.data;
// Generated Mar 6, 2016 3:14:38 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Subjects generated by hbm2java
 */
public class Subjects  implements java.io.Serializable {


     private String eqSubjectId;
     private Organizations organizations;
     private Studies studies;
     private String sponSubjectId;
     private Date dateBirth;
     private String gender;
     private Date lastUpdateDate;
     private String lastUpdateId;
     private String deleteflag;
     private String deleteby;
     private Date deleteDate;
     private String subjectStatus;
     private Set<StudySubjectMap> studySubjectMaps = new HashSet<StudySubjectMap>(0);
     private Set<Messags> messagses = new HashSet<Messags>(0);

    public Subjects() {
    }

	
    public Subjects(String eqSubjectId) {
        this.eqSubjectId = eqSubjectId;
    }
    public Subjects(String eqSubjectId, Organizations organizations, Studies studies, String sponSubjectId, Date dateBirth, String gender, Date lastUpdateDate, String lastUpdateId, String deleteflag, String deleteby, Date deleteDate, String subjectStatus, Set<StudySubjectMap> studySubjectMaps, Set<Messags> messagses) {
       this.eqSubjectId = eqSubjectId;
       this.organizations = organizations;
       this.studies = studies;
       this.sponSubjectId = sponSubjectId;
       this.dateBirth = dateBirth;
       this.gender = gender;
       this.lastUpdateDate = lastUpdateDate;
       this.lastUpdateId = lastUpdateId;
       this.deleteflag = deleteflag;
       this.deleteby = deleteby;
       this.deleteDate = deleteDate;
       this.subjectStatus = subjectStatus;
       this.studySubjectMaps = studySubjectMaps;
       this.messagses = messagses;
    }
   
    public String getEqSubjectId() {
        return this.eqSubjectId;
    }
    
    public void setEqSubjectId(String eqSubjectId) {
        this.eqSubjectId = eqSubjectId;
    }
    public Organizations getOrganizations() {
        return this.organizations;
    }
    
    public void setOrganizations(Organizations organizations) {
        this.organizations = organizations;
    }
    public Studies getStudies() {
        return this.studies;
    }
    
    public void setStudies(Studies studies) {
        this.studies = studies;
    }
    public String getSponSubjectId() {
        return this.sponSubjectId;
    }
    
    public void setSponSubjectId(String sponSubjectId) {
        this.sponSubjectId = sponSubjectId;
    }
    public Date getDateBirth() {
        return this.dateBirth;
    }
    
    public void setDateBirth(Date dateBirth) {
        this.dateBirth = dateBirth;
    }
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }
    public Date getLastUpdateDate() {
        return this.lastUpdateDate;
    }
    
    public void setLastUpdateDate(Date lastUpdateDate) {
        this.lastUpdateDate = lastUpdateDate;
    }
    public String getLastUpdateId() {
        return this.lastUpdateId;
    }
    
    public void setLastUpdateId(String lastUpdateId) {
        this.lastUpdateId = lastUpdateId;
    }
    public String getDeleteflag() {
        return this.deleteflag;
    }
    
    public void setDeleteflag(String deleteflag) {
        this.deleteflag = deleteflag;
    }
    public String getDeleteby() {
        return this.deleteby;
    }
    
    public void setDeleteby(String deleteby) {
        this.deleteby = deleteby;
    }
    public Date getDeleteDate() {
        return this.deleteDate;
    }
    
    public void setDeleteDate(Date deleteDate) {
        this.deleteDate = deleteDate;
    }
    public String getSubjectStatus() {
        return this.subjectStatus;
    }
    
    public void setSubjectStatus(String subjectStatus) {
        this.subjectStatus = subjectStatus;
    }
    public Set<StudySubjectMap> getStudySubjectMaps() {
        return this.studySubjectMaps;
    }
    
    public void setStudySubjectMaps(Set<StudySubjectMap> studySubjectMaps) {
        this.studySubjectMaps = studySubjectMaps;
    }
    public Set<Messags> getMessagses() {
        return this.messagses;
    }
    
    public void setMessagses(Set<Messags> messagses) {
        this.messagses = messagses;
    }




}


